#include <gtk/gtk.h>
#include "../controller/pthreadmon.c"

typedef struct
{
    GtkWidget *window;
    GtkWidget *grid;
    GtkWidget *startButton;
    GtkWidget *winner_label;
    GtkWidget *battle_time_label;
    GtkWidget *player1_label;
    GtkWidget *player1_pokemon1;
    GtkWidget *player1_pokemon1_time;
    GtkWidget *player1_pokemon2;
    GtkWidget *player1_pokemon2_time;
    GtkWidget *player1_pokemon3;
    GtkWidget *player1_pokemon3_time;
    GtkWidget *player1_active_label;
    GtkWidget *player1_active_name;
    GtkWidget *player1_active_image;
    GtkWidget *player1_active_hp;
    GtkWidget *player1_active_energy;
    GtkWidget *player1_fast_attack;
    GtkWidget *player1_charged_attack;
    GtkWidget *player2_label;
    GtkWidget *player2_pokemon1;
    GtkWidget *player2_pokemon1_time;
    GtkWidget *player2_pokemon2;
    GtkWidget *player2_pokemon2_time;
    GtkWidget *player2_pokemon3;
    GtkWidget *player2_pokemon3_time;
    GtkWidget *player2_active_label;
    GtkWidget *player2_active_name;
    GtkWidget *player2_active_image;
    GtkWidget *player2_active_hp;
    GtkWidget *player2_active_energy;
    GtkWidget *player2_fast_attack;
    GtkWidget *player2_charged_attack;
    GtkEntryBuffer *player1_pokemon1_buffer;
    GtkEntryBuffer *player1_pokemon2_buffer;
    GtkEntryBuffer *player1_pokemon3_buffer;
    GtkEntryBuffer *player2_pokemon1_buffer;
    GtkEntryBuffer *player2_pokemon2_buffer;
    GtkEntryBuffer *player2_pokemon3_buffer;
} app_widgets;

app_widgets *app_elements;